pseye_043:
  namespace:
    lookup_value: cameras/pseye_043
    resolve_value: true
  reference_frame:
    lookup_value: robot
    resolve_value: false
  
robot:
  odometry_topic:
    lookup_value: odometry
    resolve_value: true
  detection_topic:
    lookup_value: detections_processed
    resolve_value: true
